import type { ModelVersion } from '@/components/VersionSelector';
import type { ChangelogEntry } from '@/components/ModelChangelog';


export const versions: ModelVersion[] = [
    {
        id: 'claude-v1',
        llm: 'claude opus 4.8',
        date: 'January 2026',
        description:
            'first cut. builds the sheaf-and-closure pipeline: an event-driven micro-trajectory, an overlapping cover of [0, T], local sections with strict gluing or sheafification, pairwise and triple Cech overlap diagnostics, a moving-average coarse-graining checked for naturality, a Mori-Zwanzig memory-kernel fit with a Ljung-Box Markov test, and a calibration suite that pins the deterministic algebraic identities (cover partition, idempotent gluing, identity coarse-graining, exact linear-drift recovery).',
    },
];

export const changelog: ChangelogEntry[] = [
    {
        version: 'v1.0',
        date: 'January 2026',
        changes: [
            'site and cover: [0, T] is covered by k overlapping intervals via buildCover, with an adjustable overlap fraction.',
            'micro-process: a drift-plus-jump random walk (event rate lambda, jump scale stepSigma) generated by a seeded LCG for full determinism.',
            'descent: local sections per interval, with consistent (restriction) or inconsistent (independent) mode; strict sheaf gluing versus weighted sheafification.',
            'Cech diagnostics: pairwise overlap mismatch and triple-overlap cocycle spread, flagged against the glue tolerance epsilon.',
            'coarse-graining: a centred moving average as the macro observable, with a commutativity matrix measuring how far q is from a natural transformation.',
            'closure: Mori-Zwanzig reduced model (Markov vs exponential memory kernel), a finite-impulse-response kernel estimate with half-life, and a Ljung-Box residual test for Markovian adequacy.',
            'calibration: six deterministic checks (cover tiles the line, cover cardinality, zero-spread gluing, idempotent gluing, identity coarse-graining, exact linear-drift recovery), all computed from the logic functions.',
        ],
    },
];
