export interface Rock {
    id: string;
    name: string;
    domain: 'igneous' | 'sedimentary' | 'metamorphic';
    subdomain: string;
    description: string;
    formation: string;
    minerals: string[];
    neighbors: string[];
    transformsTo: { target: string; process: string }[];
}

export const ROCKS: Rock[] = [
    // ────────────────────────────────────────────────────────────────
    // IGNEOUS — Ultramafic
    // ────────────────────────────────────────────────────────────────
    {
        id: 'dunite',
        name: 'Dunite',
        domain: 'igneous',
        subdomain: 'ultramafic',
        description: 'Almost entirely olivine (>90%). A peridotite endmember.',
        formation: 'Crystallization from ultramafic magma in the upper mantle.',
        minerals: ['olivine'],
        neighbors: ['harzburgite', 'lherzolite', 'wehrlite'],
        transformsTo: [{ target: 'serpentinite', process: 'hydration metamorphism' }],
    },
    {
        id: 'harzburgite',
        name: 'Harzburgite',
        domain: 'igneous',
        subdomain: 'ultramafic',
        description: 'Olivine + orthopyroxene peridotite with little clinopyroxene.',
        formation: 'Residual mantle after partial melting extracts basaltic melt.',
        minerals: ['olivine', 'orthopyroxene'],
        neighbors: ['dunite', 'lherzolite'],
        transformsTo: [{ target: 'serpentinite', process: 'hydration metamorphism' }],
    },
    {
        id: 'lherzolite',
        name: 'Lherzolite',
        domain: 'igneous',
        subdomain: 'ultramafic',
        description: 'The "fertile" peridotite with both pyroxenes and olivine.',
        formation: 'Undepleted upper mantle composition.',
        minerals: ['olivine', 'orthopyroxene', 'clinopyroxene'],
        neighbors: ['harzburgite', 'wehrlite', 'dunite'],
        transformsTo: [{ target: 'serpentinite', process: 'hydration metamorphism' }],
    },
    {
        id: 'wehrlite',
        name: 'Wehrlite',
        domain: 'igneous',
        subdomain: 'ultramafic',
        description: 'Olivine + clinopyroxene peridotite with little orthopyroxene.',
        formation: 'Cumulate crystallization in layered intrusions.',
        minerals: ['olivine', 'clinopyroxene'],
        neighbors: ['lherzolite', 'clinopyroxenite'],
        transformsTo: [{ target: 'serpentinite', process: 'hydration metamorphism' }],
    },
    {
        id: 'websterite',
        name: 'Websterite',
        domain: 'igneous',
        subdomain: 'ultramafic',
        description: 'Both pyroxenes roughly equal, low olivine. A pyroxenite.',
        formation: 'Cumulate from pyroxene-saturated mafic magma.',
        minerals: ['orthopyroxene', 'clinopyroxene'],
        neighbors: ['orthopyroxenite', 'clinopyroxenite', 'lherzolite'],
        transformsTo: [{ target: 'amphibolite', process: 'metamorphism' }],
    },
    {
        id: 'orthopyroxenite',
        name: 'Orthopyroxenite',
        domain: 'igneous',
        subdomain: 'ultramafic',
        description: 'Dominated by orthopyroxene (>90% pyroxene, mostly Opx).',
        formation: 'Cumulate layer in layered mafic intrusions.',
        minerals: ['orthopyroxene'],
        neighbors: ['websterite'],
        transformsTo: [{ target: 'amphibolite', process: 'metamorphism' }],
    },
    {
        id: 'clinopyroxenite',
        name: 'Clinopyroxenite',
        domain: 'igneous',
        subdomain: 'ultramafic',
        description: 'Dominated by clinopyroxene (>90% pyroxene, mostly Cpx).',
        formation: 'Cumulate from clinopyroxene-saturated magma.',
        minerals: ['clinopyroxene'],
        neighbors: ['websterite', 'wehrlite'],
        transformsTo: [{ target: 'amphibolite', process: 'metamorphism' }],
    },
    {
        id: 'komatiite',
        name: 'Komatiite',
        domain: 'igneous',
        subdomain: 'ultramafic',
        description: 'Ultramafic volcanic rock with spinifex olivine texture. Rare, mostly Archean.',
        formation: 'Very hot mantle-derived lava (>1600°C), erupted at surface.',
        minerals: ['olivine', 'pyroxene', 'chromite'],
        neighbors: ['basalt', 'dunite'],
        transformsTo: [{ target: 'serpentinite', process: 'metamorphism' }],
    },
    {
        id: 'kimberlite',
        name: 'Kimberlite',
        domain: 'igneous',
        subdomain: 'ultramafic',
        description: 'Volatile-rich ultramafic rock, the host of diamonds.',
        formation: 'Explosive eruption from deep mantle (>150 km).',
        minerals: ['olivine', 'phlogopite', 'garnet', 'diamond'],
        neighbors: ['dunite'],
        transformsTo: [{ target: 'serpentinite', process: 'alteration' }],
    },

    // ────────────────────────────────────────────────────────────────
    // IGNEOUS — Mafic
    // ────────────────────────────────────────────────────────────────
    {
        id: 'gabbro',
        name: 'Gabbro',
        domain: 'igneous',
        subdomain: 'mafic',
        description: 'Coarse-grained mafic intrusive: plagioclase + pyroxene.',
        formation: 'Slow cooling of basaltic magma at depth.',
        minerals: ['plagioclase', 'clinopyroxene', 'olivine'],
        neighbors: ['basalt', 'diabase', 'diorite'],
        transformsTo: [
            { target: 'greenschist', process: 'low-grade metamorphism' },
            { target: 'amphibolite', process: 'medium-grade metamorphism' },
        ],
    },
    {
        id: 'basalt',
        name: 'Basalt',
        domain: 'igneous',
        subdomain: 'mafic',
        description: 'Fine-grained mafic volcanic. The most common volcanic rock on Earth.',
        formation: 'Rapid cooling of mafic lava at the surface.',
        minerals: ['plagioclase', 'pyroxene', 'olivine'],
        neighbors: ['gabbro', 'andesite'],
        transformsTo: [
            { target: 'greenschist', process: 'low-grade metamorphism' },
            { target: 'sandstone', process: 'weathering + lithification' },
        ],
    },
    {
        id: 'diabase',
        name: 'Diabase',
        domain: 'igneous',
        subdomain: 'mafic',
        description: 'Medium-grained mafic rock forming dikes and sills.',
        formation: 'Intermediate cooling rate in shallow intrusions.',
        minerals: ['plagioclase', 'pyroxene'],
        neighbors: ['gabbro', 'basalt'],
        transformsTo: [{ target: 'greenschist', process: 'metamorphism' }],
    },

    // ────────────────────────────────────────────────────────────────
    // IGNEOUS — Intermediate
    // ────────────────────────────────────────────────────────────────
    {
        id: 'diorite',
        name: 'Diorite',
        domain: 'igneous',
        subdomain: 'intermediate',
        description: 'Coarse-grained intermediate intrusive: plagioclase + hornblende.',
        formation: 'Slow cooling of intermediate magma at depth.',
        minerals: ['plagioclase', 'hornblende', 'biotite'],
        neighbors: ['andesite', 'granodiorite', 'gabbro'],
        transformsTo: [{ target: 'gneiss', process: 'high-grade metamorphism' }],
    },
    {
        id: 'andesite',
        name: 'Andesite',
        domain: 'igneous',
        subdomain: 'intermediate',
        description: 'Fine-grained intermediate volcanic. Common at subduction zones.',
        formation: 'Eruption of intermediate magma at convergent boundaries.',
        minerals: ['plagioclase', 'hornblende', 'pyroxene'],
        neighbors: ['diorite', 'basalt', 'dacite'],
        transformsTo: [{ target: 'greenschist', process: 'metamorphism' }],
    },
    {
        id: 'syenite',
        name: 'Syenite',
        domain: 'igneous',
        subdomain: 'intermediate',
        description: 'Coarse-grained, alkali-rich intermediate: alkali feldspar dominant.',
        formation: 'Crystallization of alkali-rich intermediate magma.',
        minerals: ['alkali feldspar', 'hornblende', 'biotite'],
        neighbors: ['trachyte', 'granite', 'diorite'],
        transformsTo: [{ target: 'gneiss', process: 'metamorphism' }],
    },
    {
        id: 'trachyte',
        name: 'Trachyte',
        domain: 'igneous',
        subdomain: 'intermediate',
        description: 'Fine-grained alkali-rich volcanic equivalent of syenite.',
        formation: 'Rapid cooling of alkali-rich intermediate lava.',
        minerals: ['alkali feldspar', 'biotite'],
        neighbors: ['syenite', 'andesite'],
        transformsTo: [{ target: 'sandstone', process: 'weathering + lithification' }],
    },

    // ────────────────────────────────────────────────────────────────
    // IGNEOUS — Felsic
    // ────────────────────────────────────────────────────────────────
    {
        id: 'granite',
        name: 'Granite',
        domain: 'igneous',
        subdomain: 'felsic',
        description: 'Coarse-grained felsic intrusive: quartz + feldspar + mica.',
        formation: 'Slow cooling of silica-rich magma in continental crust.',
        minerals: ['quartz', 'alkali feldspar', 'plagioclase', 'biotite', 'muscovite'],
        neighbors: ['rhyolite', 'granodiorite', 'syenite'],
        transformsTo: [
            { target: 'gneiss', process: 'high-grade metamorphism' },
            { target: 'arkose', process: 'weathering + lithification' },
        ],
    },
    {
        id: 'rhyolite',
        name: 'Rhyolite',
        domain: 'igneous',
        subdomain: 'felsic',
        description: 'Fine-grained felsic volcanic. Often forms explosive eruptions.',
        formation: 'Rapid cooling of silica-rich lava.',
        minerals: ['quartz', 'feldspar'],
        neighbors: ['granite', 'dacite', 'obsidian'],
        transformsTo: [{ target: 'sandstone', process: 'weathering + lithification' }],
    },
    {
        id: 'granodiorite',
        name: 'Granodiorite',
        domain: 'igneous',
        subdomain: 'felsic',
        description: 'Between granite and diorite: more plagioclase than alkali feldspar.',
        formation: 'Cooling of intermediate-to-felsic magma in batholiths.',
        minerals: ['plagioclase', 'quartz', 'biotite', 'hornblende'],
        neighbors: ['granite', 'diorite', 'tonalite'],
        transformsTo: [{ target: 'gneiss', process: 'metamorphism' }],
    },
    {
        id: 'dacite',
        name: 'Dacite',
        domain: 'igneous',
        subdomain: 'felsic',
        description: 'Fine-grained volcanic between andesite and rhyolite.',
        formation: 'Eruption of felsic-intermediate magma.',
        minerals: ['plagioclase', 'quartz', 'hornblende'],
        neighbors: ['andesite', 'rhyolite', 'granodiorite'],
        transformsTo: [{ target: 'sandstone', process: 'weathering + lithification' }],
    },
    {
        id: 'tonalite',
        name: 'Tonalite',
        domain: 'igneous',
        subdomain: 'felsic',
        description: 'Quartz-rich, plagioclase-dominant intrusive. Little alkali feldspar.',
        formation: 'Crystallization of hydrous, calc-alkaline magma.',
        minerals: ['plagioclase', 'quartz', 'hornblende', 'biotite'],
        neighbors: ['granodiorite', 'diorite'],
        transformsTo: [{ target: 'gneiss', process: 'metamorphism' }],
    },

    // ────────────────────────────────────────────────────────────────
    // IGNEOUS — Special
    // ────────────────────────────────────────────────────────────────
    {
        id: 'obsidian',
        name: 'Obsidian',
        domain: 'igneous',
        subdomain: 'special',
        description: 'Volcanic glass formed by extremely rapid cooling. No crystal structure.',
        formation: 'Quenching of silica-rich lava at the surface.',
        minerals: ['glass (amorphous SiO₂)'],
        neighbors: ['rhyolite', 'pumice'],
        transformsTo: [{ target: 'sandstone', process: 'weathering + lithification' }],
    },
    {
        id: 'pumice',
        name: 'Pumice',
        domain: 'igneous',
        subdomain: 'special',
        description: 'Highly vesicular volcanic glass. Can float on water.',
        formation: 'Explosive eruption trapping gas bubbles in rapidly cooling lava.',
        minerals: ['glass (amorphous SiO₂)'],
        neighbors: ['obsidian', 'rhyolite'],
        transformsTo: [{ target: 'sandstone', process: 'weathering + lithification' }],
    },
    {
        id: 'pegmatite',
        name: 'Pegmatite',
        domain: 'igneous',
        subdomain: 'special',
        description: 'Extremely coarse-grained, often with rare minerals and gems.',
        formation: 'Late-stage crystallization from volatile-rich magmatic fluids.',
        minerals: ['quartz', 'feldspar', 'mica', 'tourmaline', 'beryl'],
        neighbors: ['granite'],
        transformsTo: [{ target: 'gneiss', process: 'metamorphism' }],
    },

    // ────────────────────────────────────────────────────────────────
    // SEDIMENTARY — Clastic
    // ────────────────────────────────────────────────────────────────
    {
        id: 'claystone',
        name: 'Claystone',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Composed of clay-sized particles (<0.004 mm). Non-fissile.',
        formation: 'Compaction of clay in still water environments.',
        minerals: ['clay minerals', 'quartz'],
        neighbors: ['mudstone', 'shale'],
        transformsTo: [{ target: 'slate', process: 'low-grade metamorphism' }],
    },
    {
        id: 'mudstone',
        name: 'Mudstone',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Mix of clay and silt, non-fissile. Blocky fracture.',
        formation: 'Deposition in low-energy settings: lakes, deep sea, floodplains.',
        minerals: ['clay minerals', 'quartz', 'feldspar'],
        neighbors: ['claystone', 'shale', 'siltstone'],
        transformsTo: [{ target: 'slate', process: 'low-grade metamorphism' }],
    },
    {
        id: 'shale',
        name: 'Shale',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Fine-grained, fissile (splits into thin layers along bedding).',
        formation: 'Compaction of clay/silt with parallel mineral alignment.',
        minerals: ['clay minerals', 'quartz', 'feldspar'],
        neighbors: ['mudstone', 'siltstone'],
        transformsTo: [{ target: 'slate', process: 'low-grade metamorphism' }],
    },
    {
        id: 'siltstone',
        name: 'Siltstone',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Composed of silt-sized particles (0.004-0.063 mm).',
        formation: 'Moderate-energy deposition in rivers, deltas, and shallow seas.',
        minerals: ['quartz', 'feldspar', 'clay minerals'],
        neighbors: ['mudstone', 'sandstone'],
        transformsTo: [{ target: 'phyllite', process: 'metamorphism' }],
    },
    {
        id: 'sandstone',
        name: 'Sandstone',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Sand-sized grains (0.063-2 mm). Most common: quartz arenite.',
        formation: 'Lithification of sand in beaches, rivers, dunes, and shallow seas.',
        minerals: ['quartz', 'feldspar', 'lithic fragments'],
        neighbors: ['siltstone', 'arkose', 'graywacke'],
        transformsTo: [{ target: 'quartzite', process: 'metamorphism' }],
    },
    {
        id: 'arkose',
        name: 'Arkose',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Feldspar-rich sandstone (>25% feldspar). Pink or red color.',
        formation: 'Rapid weathering of granitic rocks in arid conditions.',
        minerals: ['quartz', 'feldspar'],
        neighbors: ['sandstone', 'graywacke'],
        transformsTo: [{ target: 'quartzite', process: 'metamorphism' }],
    },
    {
        id: 'graywacke',
        name: 'Graywacke',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Poorly sorted, dark sandstone with abundant rock fragments and clay.',
        formation: 'Turbidity currents in deep marine environments.',
        minerals: ['quartz', 'feldspar', 'rock fragments', 'clay'],
        neighbors: ['sandstone', 'arkose'],
        transformsTo: [{ target: 'schist', process: 'metamorphism' }],
    },
    {
        id: 'conglomerate',
        name: 'Conglomerate',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Rounded gravel-sized clasts (>2 mm) in a finer matrix.',
        formation: 'High-energy environments: rivers, alluvial fans, beaches.',
        minerals: ['varied clasts', 'quartz', 'feldspar'],
        neighbors: ['breccia', 'sandstone'],
        transformsTo: [{ target: 'quartzite', process: 'metamorphism' }],
    },
    {
        id: 'breccia',
        name: 'Breccia',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Angular gravel-sized clasts. Indicates short transport distance.',
        formation: 'Landslides, fault zones, volcanic collapse, or talus.',
        minerals: ['varied angular clasts'],
        neighbors: ['conglomerate'],
        transformsTo: [{ target: 'quartzite', process: 'metamorphism' }],
    },
    {
        id: 'tillite',
        name: 'Tillite',
        domain: 'sedimentary',
        subdomain: 'clastic',
        description: 'Lithified glacial till: unsorted mix of all grain sizes.',
        formation: 'Glacial deposition followed by lithification.',
        minerals: ['varied unsorted clasts'],
        neighbors: ['conglomerate', 'breccia'],
        transformsTo: [{ target: 'schist', process: 'metamorphism' }],
    },

    // ────────────────────────────────────────────────────────────────
    // SEDIMENTARY — Chemical
    // ────────────────────────────────────────────────────────────────
    {
        id: 'limestone',
        name: 'Limestone',
        domain: 'sedimentary',
        subdomain: 'chemical',
        description: 'Primarily calcium carbonate (CaCO₃). Most common carbonate rock.',
        formation: 'Precipitation from warm, shallow seas or biogenic accumulation.',
        minerals: ['calcite'],
        neighbors: ['dolostone', 'chalk', 'coquina'],
        transformsTo: [{ target: 'marble', process: 'metamorphism' }],
    },
    {
        id: 'dolostone',
        name: 'Dolostone',
        domain: 'sedimentary',
        subdomain: 'chemical',
        description: 'Magnesium-rich carbonate: CaMg(CO₃)₂.',
        formation: 'Diagenetic replacement of limestone by Mg-rich fluids.',
        minerals: ['dolomite'],
        neighbors: ['limestone'],
        transformsTo: [{ target: 'marble', process: 'metamorphism' }],
    },
    {
        id: 'chalk',
        name: 'Chalk',
        domain: 'sedimentary',
        subdomain: 'chemical',
        description: 'Soft, white limestone made of microscopic shell fragments.',
        formation: 'Accumulation of coccolithophore tests on the sea floor.',
        minerals: ['calcite'],
        neighbors: ['limestone'],
        transformsTo: [{ target: 'marble', process: 'metamorphism' }],
    },
    {
        id: 'chert',
        name: 'Chert',
        domain: 'sedimentary',
        subdomain: 'chemical',
        description: 'Microcrystalline silica. Very hard, conchoidal fracture.',
        formation: 'Precipitation of dissolved silica or replacement of carbonate.',
        minerals: ['chalcedony', 'microcrystalline quartz'],
        neighbors: ['diatomite', 'limestone'],
        transformsTo: [{ target: 'quartzite', process: 'metamorphism' }],
    },
    {
        id: 'rock-salt',
        name: 'Rock Salt',
        domain: 'sedimentary',
        subdomain: 'chemical',
        description: 'Crystalline halite (NaCl). An evaporite.',
        formation: 'Evaporation of enclosed saline water bodies.',
        minerals: ['halite'],
        neighbors: ['gypsum-rock'],
        transformsTo: [],
    },
    {
        id: 'gypsum-rock',
        name: 'Gypsum',
        domain: 'sedimentary',
        subdomain: 'chemical',
        description: 'Hydrated calcium sulfate. A common evaporite mineral.',
        formation: 'Evaporation of shallow saline water.',
        minerals: ['gypsum'],
        neighbors: ['rock-salt'],
        transformsTo: [],
    },
    {
        id: 'travertine',
        name: 'Travertine',
        domain: 'sedimentary',
        subdomain: 'chemical',
        description: 'Banded carbonate deposited from hot springs.',
        formation: 'Precipitation of CaCO₃ from supersaturated thermal water.',
        minerals: ['calcite', 'aragonite'],
        neighbors: ['limestone'],
        transformsTo: [{ target: 'marble', process: 'metamorphism' }],
    },

    // ────────────────────────────────────────────────────────────────
    // SEDIMENTARY — Organic
    // ────────────────────────────────────────────────────────────────
    {
        id: 'coal',
        name: 'Coal',
        domain: 'sedimentary',
        subdomain: 'organic',
        description: 'Combustible rock from compressed plant matter.',
        formation: 'Burial and compaction of peat over millions of years.',
        minerals: ['carbon', 'various organics'],
        neighbors: ['shale'],
        transformsTo: [{ target: 'graphite-schist', process: 'metamorphism' }],
    },
    {
        id: 'coquina',
        name: 'Coquina',
        domain: 'sedimentary',
        subdomain: 'organic',
        description: 'Poorly cemented accumulation of shell fragments.',
        formation: 'Wave action concentrating shells on beaches.',
        minerals: ['calcite (biogenic)'],
        neighbors: ['limestone'],
        transformsTo: [{ target: 'marble', process: 'metamorphism' }],
    },
    {
        id: 'diatomite',
        name: 'Diatomite',
        domain: 'sedimentary',
        subdomain: 'organic',
        description: 'Siliceous sedimentary rock from diatom frustules.',
        formation: 'Accumulation of siliceous diatom shells in lakes or oceans.',
        minerals: ['opaline silica'],
        neighbors: ['chert'],
        transformsTo: [{ target: 'quartzite', process: 'metamorphism' }],
    },

    // ────────────────────────────────────────────────────────────────
    // METAMORPHIC — Foliated
    // ────────────────────────────────────────────────────────────────
    {
        id: 'slate',
        name: 'Slate',
        domain: 'metamorphic',
        subdomain: 'foliated',
        description: 'Very low-grade, fine-grained, perfect cleavage planes.',
        formation: 'Low-grade regional metamorphism of shale/mudstone.',
        minerals: ['clay minerals', 'chlorite', 'muscovite'],
        neighbors: ['phyllite', 'shale'],
        transformsTo: [{ target: 'phyllite', process: 'increasing grade' }],
    },
    {
        id: 'phyllite',
        name: 'Phyllite',
        domain: 'metamorphic',
        subdomain: 'foliated',
        description: 'Silky sheen from fine-grained micas. Between slate and schist.',
        formation: 'Low-to-medium grade metamorphism of pelitic rocks.',
        minerals: ['muscovite', 'chlorite', 'quartz'],
        neighbors: ['slate', 'schist'],
        transformsTo: [{ target: 'schist', process: 'increasing grade' }],
    },
    {
        id: 'schist',
        name: 'Schist',
        domain: 'metamorphic',
        subdomain: 'foliated',
        description: 'Medium-grade, visible mica flakes, strong foliation.',
        formation: 'Medium-grade regional metamorphism of pelitic rocks.',
        minerals: ['muscovite', 'biotite', 'garnet', 'quartz'],
        neighbors: ['phyllite', 'gneiss'],
        transformsTo: [{ target: 'gneiss', process: 'increasing grade' }],
    },
    {
        id: 'gneiss',
        name: 'Gneiss',
        domain: 'metamorphic',
        subdomain: 'foliated',
        description: 'High-grade, compositional banding of light and dark minerals.',
        formation: 'High-grade metamorphism of pelitic or felsic protoliths.',
        minerals: ['feldspar', 'quartz', 'biotite', 'hornblende'],
        neighbors: ['schist', 'migmatite', 'granite'],
        transformsTo: [{ target: 'migmatite', process: 'partial melting' }],
    },
    {
        id: 'migmatite',
        name: 'Migmatite',
        domain: 'metamorphic',
        subdomain: 'foliated',
        description: 'Part metamorphic, part igneous — "mixed rock" with melt veins.',
        formation: 'Ultra-high-grade metamorphism with partial melting.',
        minerals: ['feldspar', 'quartz', 'biotite', 'garnet'],
        neighbors: ['gneiss', 'granite'],
        transformsTo: [{ target: 'granite', process: 'complete melting' }],
    },

    // ────────────────────────────────────────────────────────────────
    // METAMORPHIC — Mafic pathway
    // ────────────────────────────────────────────────────────────────
    {
        id: 'greenschist',
        name: 'Greenschist',
        domain: 'metamorphic',
        subdomain: 'mafic-pathway',
        description: 'Green from chlorite and epidote. Low-grade mafic metamorphic.',
        formation: 'Low-grade metamorphism of mafic rocks (basalt, gabbro).',
        minerals: ['chlorite', 'epidote', 'actinolite', 'albite'],
        neighbors: ['amphibolite', 'blueschist', 'basalt'],
        transformsTo: [{ target: 'amphibolite', process: 'increasing grade' }],
    },
    {
        id: 'amphibolite',
        name: 'Amphibolite',
        domain: 'metamorphic',
        subdomain: 'mafic-pathway',
        description: 'Medium-to-high grade, dominated by hornblende and plagioclase.',
        formation: 'Medium-grade metamorphism of mafic protoliths.',
        minerals: ['hornblende', 'plagioclase', 'garnet'],
        neighbors: ['greenschist', 'granulite', 'eclogite'],
        transformsTo: [{ target: 'granulite', process: 'increasing grade' }],
    },
    {
        id: 'granulite',
        name: 'Granulite',
        domain: 'metamorphic',
        subdomain: 'mafic-pathway',
        description: 'Very high-grade, granular texture, anhydrous minerals.',
        formation: 'High-grade metamorphism at high temperature, moderate pressure.',
        minerals: ['pyroxene', 'plagioclase', 'garnet'],
        neighbors: ['amphibolite', 'gneiss'],
        transformsTo: [{ target: 'migmatite', process: 'partial melting' }],
    },
    {
        id: 'eclogite',
        name: 'Eclogite',
        domain: 'metamorphic',
        subdomain: 'mafic-pathway',
        description: 'High-pressure, high-grade: red garnet + green omphacite.',
        formation: 'Subduction of mafic crust to >45 km depth.',
        minerals: ['garnet', 'omphacite'],
        neighbors: ['amphibolite', 'blueschist'],
        transformsTo: [{ target: 'amphibolite', process: 'decompression' }],
    },
    {
        id: 'blueschist',
        name: 'Blueschist',
        domain: 'metamorphic',
        subdomain: 'mafic-pathway',
        description: 'High-pressure, low-temperature: blue amphibole (glaucophane).',
        formation: 'Subduction zones where cold crust is rapidly buried.',
        minerals: ['glaucophane', 'lawsonite', 'epidote'],
        neighbors: ['greenschist', 'eclogite'],
        transformsTo: [{ target: 'eclogite', process: 'increasing pressure/grade' }],
    },

    // ────────────────────────────────────────────────────────────────
    // METAMORPHIC — Non-foliated
    // ────────────────────────────────────────────────────────────────
    {
        id: 'quartzite',
        name: 'Quartzite',
        domain: 'metamorphic',
        subdomain: 'non-foliated',
        description: 'Metamorphosed sandstone. Very hard, interlocking quartz grains.',
        formation: 'Recrystallization of quartz sandstone under heat and pressure.',
        minerals: ['quartz'],
        neighbors: ['sandstone', 'marble'],
        transformsTo: [],
    },
    {
        id: 'marble',
        name: 'Marble',
        domain: 'metamorphic',
        subdomain: 'non-foliated',
        description: 'Metamorphosed limestone/dolostone. Interlocking calcite crystals.',
        formation: 'Recrystallization of carbonate rocks under heat and pressure.',
        minerals: ['calcite', 'dolomite'],
        neighbors: ['limestone', 'quartzite'],
        transformsTo: [],
    },
    {
        id: 'hornfels',
        name: 'Hornfels',
        domain: 'metamorphic',
        subdomain: 'non-foliated',
        description: 'Fine-grained, hard contact metamorphic rock. No foliation.',
        formation: 'Contact metamorphism adjacent to igneous intrusions.',
        minerals: ['andalusite', 'cordierite', 'biotite'],
        neighbors: ['slate', 'schist'],
        transformsTo: [],
    },

    // ────────────────────────────────────────────────────────────────
    // METAMORPHIC — Ultramafic
    // ────────────────────────────────────────────────────────────────
    {
        id: 'serpentinite',
        name: 'Serpentinite',
        domain: 'metamorphic',
        subdomain: 'ultramafic-meta',
        description: 'Green, waxy, from hydration of olivine-rich rocks.',
        formation: 'Low-grade hydration metamorphism of peridotite.',
        minerals: ['serpentine', 'magnetite', 'chrysotile'],
        neighbors: ['soapstone', 'dunite'],
        transformsTo: [{ target: 'soapstone', process: 'CO₂ metasomatism' }],
    },
    {
        id: 'soapstone',
        name: 'Soapstone',
        domain: 'metamorphic',
        subdomain: 'ultramafic-meta',
        description: 'Soft, talc-rich rock. Feels soapy. Carved easily.',
        formation: 'Metasomatism of serpentinite with CO₂-rich fluids.',
        minerals: ['talc', 'chlorite', 'magnetite'],
        neighbors: ['serpentinite'],
        transformsTo: [],
    },

    // ────────────────────────────────────────────────────────────────
    // METAMORPHIC — Other
    // ────────────────────────────────────────────────────────────────
    {
        id: 'mylonite',
        name: 'Mylonite',
        domain: 'metamorphic',
        subdomain: 'other',
        description: 'Intensely deformed rock from ductile shear zones.',
        formation: 'Extreme ductile deformation along fault zones at depth.',
        minerals: ['quartz', 'feldspar (ribbon-textured)'],
        neighbors: ['gneiss', 'schist'],
        transformsTo: [],
    },
    {
        id: 'skarn',
        name: 'Skarn',
        domain: 'metamorphic',
        subdomain: 'other',
        description: 'Contact metasomatic rock, rich in Ca-Mg-Fe silicates and ore minerals.',
        formation: 'Hot fluids from intrusion reacting with carbonate country rock.',
        minerals: ['garnet', 'pyroxene', 'wollastonite', 'calcite'],
        neighbors: ['marble', 'hornfels'],
        transformsTo: [],
    },
];
