import type { StateSpace } from './index';

export const STATE_SPACES: StateSpace[] = [
    // ── Row 1: Geometry ──────────────────────────────────────────
    {
        id: 'FD',
        name: 'Finite Discrete',
        family: 'geometry',
        row: 1, col: 1,
        short: 'enumerable states',
        summary: 'The state space is a finite set. Every state can be listed and every transition enumerated. Finite automata, board games, and digital circuits inhabit this world. Computation here is exhaustive search or clever pruning.',
        examples: ['Finite automata', 'Chess positions', 'Boolean circuits', 'Petri nets'],
        tags: ['discrete', 'finite', 'combinatorial'],
        scores: { dimensionality: 0, stochasticity: 0, nonlinearity: 1, observability: 4, controllability: 3, openness: 0, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 4 },
        keyQuestion: 'Can every state be enumerated?',
        note: 'The simplest state spaces. Complexity arises from combinatorial explosion, not geometric structure.',
        ancestors: ['Turing', 'Shannon'],
    },
    {
        id: 'CD',
        name: 'Countable Discrete',
        family: 'geometry',
        row: 1, col: 2,
        short: 'unbounded countable states',
        summary: 'States are countably infinite — queues that grow without bound, random walks on integers, Markov chains on countable sets. The key distinction from finite discrete: no ceiling on state values, so recurrence and transience become meaningful.',
        examples: ['Queuing systems', 'Random walks on ℤ', 'Markov chains', 'Population counts'],
        tags: ['discrete', 'countable', 'stochastic'],
        scores: { dimensionality: 1, stochasticity: 2, nonlinearity: 1, observability: 3, controllability: 2, openness: 1, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 3 },
        keyQuestion: 'Are states countable but unbounded?',
        note: 'Recurrence vs transience replaces ergodicity as the central question.',
        ancestors: ['Markov', 'Erlang'],
    },
    {
        id: 'CF',
        name: 'Continuous Finite-Dim',
        family: 'geometry',
        row: 1, col: 3,
        short: 'ℝⁿ phase spaces',
        summary: 'The state space is ℝⁿ for some finite n. Classical ODE systems, mechanical phase spaces, chemical kinetics with finitely many species. The bread and butter of mathematical physics since Newton.',
        examples: ['Pendulum phase space', 'Lotka-Volterra equations', 'Chemical reaction networks', 'Rigid body dynamics'],
        tags: ['continuous', 'finite-dimensional', 'ODE'],
        scores: { dimensionality: 2, stochasticity: 0, nonlinearity: 2, observability: 3, controllability: 3, openness: 1, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 3 },
        keyQuestion: 'Is the state a finite-dimensional real vector?',
        note: 'Most of classical physics lives here. Geometric structure (manifolds, symplectic forms) enriches the topology.',
        ancestors: ['Newton', 'Poincaré', 'Arnold'],
    },
    {
        id: 'IF',
        name: 'Infinite-Dim',
        family: 'geometry',
        row: 1, col: 4,
        short: 'function/field spaces',
        summary: 'States are functions, fields, or distributions. PDE systems, quantum field theory, fluid velocity fields. The state space is a function space (Hilbert, Sobolev, etc.) with infinite degrees of freedom.',
        examples: ['Navier-Stokes velocity fields', 'Quantum wave functions', 'Elastic deformation fields', 'Electromagnetic fields'],
        tags: ['infinite-dimensional', 'PDE', 'functional'],
        scores: { dimensionality: 4, stochasticity: 1, nonlinearity: 3, observability: 2, controllability: 1, openness: 1, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 2 },
        keyQuestion: 'Is the state a function or field rather than a vector?',
        note: 'Infinite dimensions introduce qualitatively new phenomena: turbulence, renormalization, spontaneous symmetry breaking.',
        ancestors: ['Euler', 'Hilbert', 'Dirac'],
    },
    {
        id: 'HY',
        name: 'Hybrid',
        family: 'geometry',
        row: 1, col: 5,
        short: 'continuous + discrete jumps',
        summary: 'Continuous flows interspersed with discrete mode switches. Cyber-physical systems, bouncing balls, gene regulatory networks with toggle switches. The state space is a product of ℝⁿ and a finite set of modes.',
        examples: ['Thermostat control', 'Bouncing ball', 'Gene toggle switches', 'Autonomous vehicles'],
        tags: ['hybrid', 'cyber-physical', 'switching'],
        scores: { dimensionality: 2, stochasticity: 1, nonlinearity: 3, observability: 2, controllability: 2, openness: 2, adaptation: 1, endogeneity: 0, reflexivity: 0, predictability: 2 },
        keyQuestion: 'Does the system combine continuous flow with discrete switching?',
        note: 'Zeno phenomena (infinitely many switches in finite time) reveal deep difficulties at the continuous-discrete interface.',
        ancestors: ['Henzinger', 'Branicky'],
    },

    // ── Row 2: Dynamics ──────────────────────────────────────────
    {
        id: 'HM',
        name: 'Hamiltonian',
        family: 'dynamics',
        row: 2, col: 1,
        short: 'symplectic, energy-conserving',
        summary: 'Dynamics preserve a symplectic form and conserve energy. Phase space volume is invariant (Liouville). Celestial mechanics, charged particles in fields, ideal fluids. The gold standard of deterministic, reversible dynamics.',
        examples: ['Planetary orbits', 'Charged particle in EM field', 'Ideal pendulum', 'Molecular dynamics'],
        tags: ['symplectic', 'conservative', 'reversible'],
        scores: { dimensionality: 2, stochasticity: 0, nonlinearity: 2, observability: 4, controllability: 2, openness: 0, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 4 },
        keyQuestion: 'Does the system conserve energy and phase-space volume?',
        note: 'Hamiltonian structure is so rigid that knowing it exists already constrains the dynamics enormously.',
        ancestors: ['Hamilton', 'Liouville', 'Arnold'],
    },
    {
        id: 'LN',
        name: 'Linear',
        family: 'dynamics',
        row: 2, col: 2,
        short: 'superposition holds',
        summary: 'Dynamics obey superposition: the response to a sum of inputs equals the sum of responses. Circuits, linear control systems, Fourier analysis. Linear algebra is the complete toolkit.',
        examples: ['RLC circuits', 'Linear control systems', 'Fourier optics', 'Small-signal models'],
        tags: ['linear', 'superposition', 'spectral'],
        scores: { dimensionality: 2, stochasticity: 0, nonlinearity: 0, observability: 4, controllability: 4, openness: 1, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 4 },
        keyQuestion: 'Does superposition hold?',
        note: 'Linearity is the exception, not the rule — but an extraordinarily productive exception.',
        ancestors: ['Fourier', 'Kalman', 'Bode'],
    },
    {
        id: 'NL',
        name: 'Nonlinear',
        family: 'dynamics',
        row: 2, col: 3,
        short: 'bifurcations, attractors',
        summary: 'Superposition fails. Small causes can have large effects; new qualitative behaviors (limit cycles, bifurcations, strange attractors) emerge that have no linear analog. Most real-world dynamics are here.',
        examples: ['Predator-prey oscillations', 'Belousov-Zhabotinsky reaction', 'Neural firing', 'Climate oscillations'],
        tags: ['nonlinear', 'bifurcation', 'attractor'],
        scores: { dimensionality: 2, stochasticity: 1, nonlinearity: 4, observability: 2, controllability: 1, openness: 2, adaptation: 1, endogeneity: 0, reflexivity: 0, predictability: 2 },
        keyQuestion: 'Do small perturbations produce qualitatively different behavior?',
        note: 'Nonlinearity is generic — linearity is the special case that happens to be analytically tractable.',
        ancestors: ['Poincaré', 'Lorenz', 'Strogatz'],
    },
    {
        id: 'ST',
        name: 'Stochastic',
        family: 'dynamics',
        row: 2, col: 4,
        short: 'noise-driven dynamics',
        summary: 'Intrinsic randomness is part of the dynamics, not merely measurement error. Brownian motion, gene expression noise, financial volatility. The state is a probability distribution evolving via Fokker-Planck or Itô calculus.',
        examples: ['Brownian motion', 'Gene expression noise', 'Option pricing', 'Radioactive decay'],
        tags: ['stochastic', 'noise', 'probability'],
        scores: { dimensionality: 2, stochasticity: 4, nonlinearity: 2, observability: 2, controllability: 1, openness: 2, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 1 },
        keyQuestion: 'Is randomness intrinsic to the dynamics rather than just measurement?',
        note: 'Noise can be constructive: stochastic resonance, noise-induced transitions, exploration in optimization.',
        ancestors: ['Einstein', 'Wiener', 'Itô'],
    },
    {
        id: 'CH',
        name: 'Chaotic',
        family: 'dynamics',
        row: 2, col: 5,
        short: 'sensitive dependence',
        summary: 'Deterministic but unpredictable. Exponential sensitivity to initial conditions (positive Lyapunov exponents) creates a prediction horizon beyond which forecasting is impossible. Weather, turbulence, three-body problem.',
        examples: ['Weather systems', 'Turbulent flow', 'Three-body problem', 'Double pendulum'],
        tags: ['chaos', 'Lyapunov', 'sensitive-dependence'],
        scores: { dimensionality: 2, stochasticity: 0, nonlinearity: 4, observability: 2, controllability: 0, openness: 1, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 0 },
        keyQuestion: 'Does the system have a finite Lyapunov prediction horizon?',
        note: 'Chaos is deterministic — the randomness is epistemic, not ontological. But the distinction may not matter in practice.',
        ancestors: ['Lorenz', 'Ruelle', 'Mandelbrot'],
    },

    // ── Row 3: Control ───────────────────────────────────────────
    {
        id: 'OB',
        name: 'Observable',
        family: 'control',
        row: 3, col: 1,
        short: 'state inferable from outputs',
        summary: 'The full internal state can be reconstructed from output measurements. Observability is the dual of controllability in linear systems. Sensor fusion, state estimation, and Kalman filtering rely on this property.',
        examples: ['Kalman filter', 'GPS state estimation', 'Observer design', 'Tomographic imaging'],
        tags: ['observable', 'estimation', 'sensor'],
        scores: { dimensionality: 2, stochasticity: 1, nonlinearity: 1, observability: 4, controllability: 2, openness: 1, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 3 },
        keyQuestion: 'Can the internal state be reconstructed from outputs?',
        note: 'Observability is not about having enough sensors — it is about whether the dynamics couple the hidden state to the output at all.',
        ancestors: ['Kalman', 'Luenberger'],
    },
    {
        id: 'CT',
        name: 'Controllable',
        family: 'control',
        row: 3, col: 2,
        short: 'inputs can steer the state',
        summary: 'Any state can be reached from any other via appropriate inputs. The system is fully steerable. Robotics, process control, spacecraft attitude. Controllability guarantees that the control problem has a solution.',
        examples: ['Robotic arm', 'Aircraft autopilot', 'Chemical reactor', 'Satellite attitude control'],
        tags: ['controllable', 'reachable', 'steerable'],
        scores: { dimensionality: 2, stochasticity: 0, nonlinearity: 1, observability: 3, controllability: 4, openness: 1, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 3 },
        keyQuestion: 'Can inputs steer the system to any desired state?',
        note: 'Controllability is a structural property of the system, not of the controller.',
        ancestors: ['Kalman', 'Pontryagin'],
    },
    {
        id: 'PO',
        name: 'Partially Observable',
        family: 'control',
        row: 3, col: 3,
        short: 'hidden state, belief space',
        summary: 'The agent cannot see the full state. Decision-making occurs in belief space — probability distributions over hidden states. Medical diagnosis, macroeconomic policy, poker. POMDPs are PSPACE-complete.',
        examples: ['Medical diagnosis', 'Macro policy under uncertainty', 'Poker AI', 'Hidden Markov models'],
        tags: ['partial-observability', 'belief-space', 'POMDP'],
        scores: { dimensionality: 3, stochasticity: 3, nonlinearity: 2, observability: 1, controllability: 1, openness: 2, adaptation: 1, endogeneity: 1, reflexivity: 0, predictability: 1 },
        keyQuestion: 'Must the agent reason over beliefs about hidden states?',
        note: 'Partial observability transforms a Markov problem into an infinite-dimensional belief-space problem.',
        ancestors: ['Kaelbling', 'Cassandra', 'Astrom'],
    },
    {
        id: 'OC',
        name: 'Optimal Control',
        family: 'control',
        row: 3, col: 4,
        short: 'cost-minimizing trajectories',
        summary: 'Among all feasible trajectories, find the one minimizing a cost functional. Bellman\'s dynamic programming and Pontryagin\'s maximum principle provide the two main solution frameworks. Rocket trajectories, portfolio optimization, neural motor control.',
        examples: ['Rocket trajectory', 'Portfolio optimization', 'LQR regulator', 'Motor control in the brain'],
        tags: ['optimal', 'Bellman', 'Pontryagin'],
        scores: { dimensionality: 2, stochasticity: 1, nonlinearity: 2, observability: 3, controllability: 3, openness: 1, adaptation: 1, endogeneity: 0, reflexivity: 0, predictability: 3 },
        keyQuestion: 'Is there a cost functional being minimized over trajectories?',
        note: 'Optimal control unifies physics (least action) with engineering (minimum cost) and economics (utility maximization).',
        ancestors: ['Bellman', 'Pontryagin', 'Kalman'],
    },
    {
        id: 'DC',
        name: 'Decentralized',
        family: 'control',
        row: 3, col: 5,
        short: 'no single controller',
        summary: 'No single agent has full information or full authority. Multiple controllers with local information must coordinate without a central planner. Swarm robotics, internet protocols, market mechanisms.',
        examples: ['Swarm robotics', 'Internet routing (BGP)', 'Power grid balancing', 'Ant colony foraging'],
        tags: ['decentralized', 'distributed', 'multi-agent'],
        scores: { dimensionality: 3, stochasticity: 2, nonlinearity: 3, observability: 1, controllability: 1, openness: 3, adaptation: 2, endogeneity: 2, reflexivity: 1, predictability: 1 },
        keyQuestion: 'Does the system lack a central controller with full information?',
        note: 'Decentralization is not a deficiency — it is often a design choice for robustness and scalability.',
        ancestors: ['Witsenhausen', 'Tsitsiklis'],
    },

    // ── Row 4: Systems ───────────────────────────────────────────
    {
        id: 'OP',
        name: 'Open',
        family: 'systems',
        row: 4, col: 1,
        short: 'environment co-defines dynamics',
        summary: 'The system exchanges matter, energy, or information with its environment. The boundary is real but permeable. Organisms, firms, ecosystems. Far-from-equilibrium thermodynamics governs the steady states.',
        examples: ['Living organisms', 'Firms in markets', 'Convection cells', 'Cities'],
        tags: ['open-system', 'boundary', 'exchange'],
        scores: { dimensionality: 3, stochasticity: 2, nonlinearity: 3, observability: 2, controllability: 1, openness: 4, adaptation: 2, endogeneity: 2, reflexivity: 0, predictability: 1 },
        keyQuestion: 'Does the system exchange matter, energy, or information with an environment?',
        note: 'Closed systems tend toward equilibrium. Open systems can maintain structure precisely because they are open.',
        ancestors: ['Bertalanffy', 'Prigogine'],
    },
    {
        id: 'FB',
        name: 'Feedback',
        family: 'systems',
        row: 4, col: 2,
        short: 'output→input loops',
        summary: 'Outputs feed back as inputs. Negative feedback stabilizes (homeostasis); positive feedback amplifies (explosions, bubbles). The simplest mechanism for self-regulation and also for catastrophic runaway.',
        examples: ['Thermostat', 'Blood glucose regulation', 'Audio feedback', 'Price-supply loops'],
        tags: ['feedback', 'loop', 'homeostasis'],
        scores: { dimensionality: 2, stochasticity: 1, nonlinearity: 3, observability: 3, controllability: 2, openness: 2, adaptation: 2, endogeneity: 1, reflexivity: 0, predictability: 2 },
        keyQuestion: 'Does system output feed back as input?',
        note: 'Feedback is neither good nor bad — negative feedback stabilizes, positive feedback can either innovate or destroy.',
        ancestors: ['Wiener', 'Ashby', 'Black'],
    },
    {
        id: 'AD',
        name: 'Adaptive',
        family: 'systems',
        row: 4, col: 3,
        short: 'rules update through experience',
        summary: 'The system modifies its parameters or structure based on experience. Immune systems learn pathogens, neural networks adjust weights, organisms habituate. The update rule itself is fixed — only the parameters change.',
        examples: ['Immune system', 'Neural plasticity', 'Reinforcement learning', 'Bacterial chemotaxis'],
        tags: ['adaptive', 'learning', 'plasticity'],
        scores: { dimensionality: 3, stochasticity: 2, nonlinearity: 3, observability: 2, controllability: 1, openness: 3, adaptation: 4, endogeneity: 1, reflexivity: 0, predictability: 1 },
        keyQuestion: 'Does the system modify its own parameters through experience?',
        note: 'Adaptation is the bridge between fixed laws and full endogeneity — the rules that change are specified by meta-rules that don\'t.',
        ancestors: ['Ashby', 'Holland', 'Hebb'],
    },
    {
        id: 'SO',
        name: 'Self-Organizing',
        family: 'systems',
        row: 4, col: 4,
        short: 'order from local interactions',
        summary: 'Global order emerges from local interactions without central direction. Flocking, Turing patterns, crystallization, traffic jams. The macro pattern is not encoded in any single agent\'s rules.',
        examples: ['Flocking/swarming', 'Turing reaction-diffusion', 'Crystallization', 'Spontaneous traffic jams'],
        tags: ['self-organization', 'emergence', 'local-rules'],
        scores: { dimensionality: 3, stochasticity: 2, nonlinearity: 3, observability: 2, controllability: 0, openness: 2, adaptation: 2, endogeneity: 1, reflexivity: 0, predictability: 1 },
        keyQuestion: 'Does global order arise from purely local interactions?',
        note: 'Self-organization is not magic — it is the inevitable result of iterated local interactions with the right nonlinearities.',
        ancestors: ['Turing', 'Haken', 'Kauffman'],
    },
    {
        id: 'HR',
        name: 'Hierarchical',
        family: 'systems',
        row: 4, col: 5,
        short: 'nested subsystems, multi-scale',
        summary: 'The system is composed of nested subsystems operating at different scales. Cells within organs within organisms, departments within firms within industries. Each level has its own dynamics constrained by levels above and below.',
        examples: ['Organisms (cell → organ → body)', 'Corporations', 'Ecosystems', 'Computer architecture'],
        tags: ['hierarchy', 'multi-scale', 'nesting'],
        scores: { dimensionality: 3, stochasticity: 2, nonlinearity: 3, observability: 2, controllability: 1, openness: 3, adaptation: 2, endogeneity: 2, reflexivity: 0, predictability: 1 },
        keyQuestion: 'Are there nested subsystems operating at different spatial or temporal scales?',
        note: 'Hierarchies emerge when inter-level coupling is weak enough for near-decomposability but strong enough for coordination.',
        ancestors: ['Simon', 'Koestler', 'Salthe'],
    },

    // ── Row 5: Social ────────────────────────────────────────────
    {
        id: 'EN',
        name: 'Endogenous',
        family: 'social',
        row: 5, col: 1,
        short: 'rules generated inside',
        summary: 'The rules of the system are not given from outside but generated by the agents within it. Markets create prices, legislatures create laws, cultures create norms. The Lucas critique: policy changes alter the very model being used.',
        examples: ['Market price formation', 'Legal systems', 'Cultural norms', 'Institutional evolution'],
        tags: ['endogenous', 'institution', 'norm'],
        scores: { dimensionality: 3, stochasticity: 3, nonlinearity: 3, observability: 1, controllability: 1, openness: 4, adaptation: 3, endogeneity: 4, reflexivity: 2, predictability: 1 },
        keyQuestion: 'Are the rules of the system generated by its own participants?',
        note: 'The Lucas critique is the formal statement: any policy evaluated under current rules will change the rules.',
        ancestors: ['Lucas', 'Hayek', 'North'],
    },
    {
        id: 'RF',
        name: 'Reflexive',
        family: 'social',
        row: 5, col: 2,
        short: 'beliefs alter reality',
        summary: 'Participants\' models of the system feed back into the system\'s dynamics. A bank run happens because people believe it will. Soros\'s reflexivity: the cognitive function (understanding) and the participating function (acting) interfere with each other.',
        examples: ['Bank runs', 'Self-fulfilling prophecies', 'Speculative bubbles', 'Currency crises'],
        tags: ['reflexive', 'self-fulfilling', 'Soros'],
        scores: { dimensionality: 3, stochasticity: 3, nonlinearity: 4, observability: 1, controllability: 0, openness: 4, adaptation: 3, endogeneity: 4, reflexivity: 4, predictability: 0 },
        keyQuestion: 'Do participants\' beliefs about the system alter the system itself?',
        note: 'Reflexivity is not bias or irrationality — it is a structural feature of systems where observers are also participants.',
        ancestors: ['Soros', 'Merton', 'Keynes'],
    },
    {
        id: 'S2',
        name: 'Second-Order',
        family: 'social',
        row: 5, col: 3,
        short: 'observer included in system',
        summary: 'The observer is part of the system being observed. Second-order cybernetics: the act of observing, modeling, or intervening changes the system. Social science, psychotherapy, participatory action research.',
        examples: ['Psychotherapy', 'Participatory research', 'AI alignment', 'Anthropological fieldwork'],
        tags: ['second-order', 'observer', 'cybernetics'],
        scores: { dimensionality: 3, stochasticity: 3, nonlinearity: 3, observability: 1, controllability: 0, openness: 4, adaptation: 3, endogeneity: 3, reflexivity: 4, predictability: 0 },
        keyQuestion: 'Is the observer included in the system being observed?',
        note: 'First-order science observes the world. Second-order science observes the observing — and realizes the observation changes the world.',
        ancestors: ['von Foerster', 'Maturana', 'Luhmann'],
    },
    {
        id: 'GT',
        name: 'Game-Theoretic',
        family: 'social',
        row: 5, col: 4,
        short: 'strategic multi-agent',
        summary: 'Multiple agents with conflicting or aligned interests choose strategies simultaneously or sequentially. Nash equilibria, mechanism design, evolutionary game theory. The state includes each agent\'s beliefs about others\' strategies.',
        examples: ['Auctions', 'Arms races', 'Evolutionary strategies', 'Oligopoly pricing'],
        tags: ['game-theory', 'strategic', 'Nash'],
        scores: { dimensionality: 3, stochasticity: 2, nonlinearity: 3, observability: 1, controllability: 1, openness: 3, adaptation: 2, endogeneity: 3, reflexivity: 2, predictability: 1 },
        keyQuestion: 'Do strategic interactions between agents determine the dynamics?',
        note: 'Game theory is the mathematics of conflict and cooperation — the dynamics depend on what each agent thinks the others will do.',
        ancestors: ['von Neumann', 'Nash', 'Maynard Smith'],
    },
    {
        id: 'PF',
        name: 'Performative',
        family: 'social',
        row: 5, col: 5,
        short: 'measurement changes the measured',
        summary: 'The act of measuring, rating, or ranking changes the thing being measured. University rankings change university behavior. Economic indicators become targets (Goodhart\'s law). Credit scores reshape credit markets.',
        examples: ['University rankings', 'Credit scores', 'Economic indicators (Goodhart)', 'Election polls'],
        tags: ['performative', 'Goodhart', 'reactivity'],
        scores: { dimensionality: 3, stochasticity: 3, nonlinearity: 4, observability: 1, controllability: 0, openness: 3, adaptation: 3, endogeneity: 4, reflexivity: 4, predictability: 0 },
        keyQuestion: 'Does measurement change the thing being measured?',
        note: 'Goodhart\'s law is the special case; performativity is the general structure. Any metric that becomes a target ceases to be a good metric.',
        ancestors: ['Goodhart', 'Campbell', 'MacKenzie'],
    },

    // ── Row 6: Epistemology ──────────────────────────────────────
    {
        id: 'DS',
        name: 'Dissipative',
        family: 'epistemology',
        row: 6, col: 1,
        short: 'attractors, information loss',
        summary: 'Energy is dissipated and information about initial conditions is lost. Trajectories converge onto attractors (fixed points, limit cycles, strange attractors). Most real-world systems are dissipative — Hamiltonian perfection is the idealization.',
        examples: ['Damped oscillator', 'Rayleigh-Bénard convection', 'Laser dynamics', 'Neural attractor networks'],
        tags: ['dissipative', 'attractor', 'irreversible'],
        scores: { dimensionality: 2, stochasticity: 1, nonlinearity: 3, observability: 3, controllability: 2, openness: 2, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 3 },
        keyQuestion: 'Do trajectories converge onto attractors with information loss?',
        note: 'Dissipation is epistemologically useful — it means the system forgets its initial conditions and becomes predictable on the attractor.',
        ancestors: ['Lorenz', 'Ruelle', 'Prigogine'],
    },
    {
        id: 'GD',
        name: 'Gradient',
        family: 'epistemology',
        row: 6, col: 2,
        short: 'dynamics follow a potential',
        summary: 'The system evolves by descending (or ascending) a potential landscape. No oscillations, no chaos — only convergence to local optima. Gradient descent in ML, potential energy minimization, Lyapunov stability.',
        examples: ['Neural network training (SGD)', 'Protein folding', 'Energy minimization', 'Waddington landscape'],
        tags: ['gradient', 'potential', 'optimization'],
        scores: { dimensionality: 3, stochasticity: 1, nonlinearity: 2, observability: 3, controllability: 2, openness: 1, adaptation: 1, endogeneity: 0, reflexivity: 0, predictability: 3 },
        keyQuestion: 'Does the system follow a gradient of some potential function?',
        note: 'Gradient dynamics guarantee convergence but not to the global optimum — the landscape\'s topology determines which basin you fall into.',
        ancestors: ['Cauchy', 'Lyapunov', 'Waddington'],
    },
    {
        id: 'ER',
        name: 'Ergodic',
        family: 'epistemology',
        row: 6, col: 3,
        short: 'time average = ensemble average',
        summary: 'A single trajectory, if run long enough, visits every region of state space in proportion to its probability measure. Time averages equal ensemble averages. This is the foundation of statistical mechanics and thermodynamic reasoning.',
        examples: ['Ideal gas in equilibrium', 'Ergodic Markov chains', 'Mixing in fluids', 'Hash functions'],
        tags: ['ergodic', 'statistical-mechanics', 'mixing'],
        scores: { dimensionality: 3, stochasticity: 2, nonlinearity: 2, observability: 3, controllability: 1, openness: 0, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 3 },
        keyQuestion: 'Does the time average of a single trajectory equal the ensemble average?',
        note: 'Non-ergodicity breaks statistical mechanics. Economics, growth, and survival are fundamentally non-ergodic — what matters is your trajectory, not the ensemble.',
        ancestors: ['Boltzmann', 'Birkhoff', 'Peters'],
    },
    {
        id: 'MF',
        name: 'Manifold',
        family: 'epistemology',
        row: 6, col: 4,
        short: 'curved geometry, fiber bundles',
        summary: 'The state space has intrinsic curvature or nontrivial topology. General relativity (spacetime is a pseudo-Riemannian manifold), gauge theory (fiber bundles), configuration spaces of robots with constraints.',
        examples: ['Spacetime in GR', 'Gauge fields', 'Robot configuration spaces', 'Shape spaces'],
        tags: ['manifold', 'curvature', 'topology'],
        scores: { dimensionality: 3, stochasticity: 0, nonlinearity: 3, observability: 2, controllability: 1, openness: 0, adaptation: 0, endogeneity: 0, reflexivity: 0, predictability: 2 },
        keyQuestion: 'Does the state space have intrinsic curvature or nontrivial topology?',
        note: 'When the state space is curved, "straight line" (geodesic) is the best you can do — and geodesics encode the physics.',
        ancestors: ['Riemann', 'Einstein', 'Yang-Mills'],
    },
    {
        id: 'NW',
        name: 'Network',
        family: 'epistemology',
        row: 6, col: 5,
        short: 'topology > metric, graphs',
        summary: 'The state space is a graph or network. What matters is connectivity (topology), not distance (metric). Neural networks, social networks, transport networks, gene regulatory networks. Degree distributions, clustering, small-world properties.',
        examples: ['Social networks', 'Neural connectomes', 'Internet topology', 'Gene regulatory networks'],
        tags: ['network', 'graph', 'topology'],
        scores: { dimensionality: 3, stochasticity: 2, nonlinearity: 3, observability: 2, controllability: 1, openness: 2, adaptation: 2, endogeneity: 1, reflexivity: 0, predictability: 1 },
        keyQuestion: 'Is connectivity structure more important than metric distance?',
        note: 'Network science revealed that most real-world networks are neither regular nor random — they have heavy tails, small worlds, and modular structure.',
        ancestors: ['Euler', 'Erdős', 'Barabási'],
    },
];
