export type Topic =
    | 'mathematics'
    | 'physics'
    | 'chemistry'
    | 'biology'
    | 'neuroscience'
    | 'computer-science'
    | 'economics'
    | 'political-science'
    | 'psychology'
    | 'sociology'
    | 'philosophy'
    | 'aesthetics';

export type Operation =
    | 'landscape'
    | 'threshold'
    | 'symmetry'
    | 'morphogenesis'
    | 'anatomy'
    | 'tension';

export const TOPICS: { key: Topic; label: string; description: string }[] = [
    { key: 'mathematics', label: 'mathematics', description: 'pure structures: algebra, topology, geometry, number theory' },
    { key: 'physics', label: 'physics', description: 'matter, energy, and fundamental forces' },
    { key: 'chemistry', label: 'chemistry', description: 'molecular structure, bonding, and reactions' },
    { key: 'biology', label: 'biology', description: 'living systems, evolution, and development' },
    { key: 'neuroscience', label: 'neuroscience', description: 'brain, perception, and consciousness' },
    { key: 'computer-science', label: 'computer science', description: 'algorithms, computation, and information' },
    { key: 'economics', label: 'economics', description: 'markets, incentives, and resource allocation' },
    { key: 'political-science', label: 'political science', description: 'governance, power, and collective choice' },
    { key: 'psychology', label: 'psychology', description: 'mind, behavior, and cognition' },
    { key: 'sociology', label: 'sociology', description: 'social structures and collective dynamics' },
    { key: 'philosophy', label: 'philosophy', description: 'logic, ethics, and epistemology' },
    { key: 'aesthetics', label: 'aesthetics', description: 'pattern, harmony, and form' },
];

export const OPERATIONS: { key: Operation; label: string; description: string; question: string }[] = [
    { key: 'landscape', label: 'landscape', description: 'mapping a possibility space', question: 'what does the terrain look like?' },
    { key: 'threshold', label: 'threshold', description: 'finding where a system changes regime', question: 'when does it flip?' },
    { key: 'symmetry', label: 'symmetry', description: 'what stays the same under transformation', question: 'what is preserved?' },
    { key: 'morphogenesis', label: 'morphogenesis', description: 'watching form emerge from process', question: 'how does form arise?' },
    { key: 'anatomy', label: 'anatomy', description: 'dissecting structure into working parts', question: 'what\'s inside?' },
    { key: 'tension', label: 'tension', description: 'tracing opposing forces that hold a system together', question: 'what pulls against what?' },
];

export const playgrounds: {
    name: string;
    link: string;
    description: string;
    date: string;
    topics: Topic[];
    operations: Operation[];
}[] = [
    {
        name: 'self-sorted arrays',
        link: '/playgrounds/self-sorted-arrays',
        description: 'cell-based sorting algorithms',
        date: 'February 2024',
        topics: ['computer-science', 'mathematics'],
        operations: ['morphogenesis'],
    },
    {
        name: 'estigrade',
        link: '/playgrounds/estigrade',
        description: 'grade estimation',
        date: 'September 2024',
        topics: ['mathematics'],
        operations: ['anatomy'],
    },
    {
        name: 'coasellular morphogenesis',
        link: '/playgrounds/coasellular-morphogenesis',
        description: 'Coase theorem applied to cellular development and transaction costs',
        date: 'November 2024',
        topics: ['biology', 'economics'],
        operations: ['morphogenesis', 'tension'],
    },
    {
        name: 'fracqunx',
        link: '/playgrounds/fracqunx',
        description: 'fractional quincunx',
        date: 'February 2025',
        topics: ['mathematics'],
        operations: ['landscape'],
    },
    {
        name: 'Halley window',
        link: '/playgrounds/halley-window',
        description: 'Halley\'s method fractal patterns',
        date: 'February 2025',
        topics: ['mathematics'],
        operations: ['landscape', 'symmetry'],
    },
    {
        name: 'eyevolution',
        link: '/playgrounds/eyevolution',
        description: 'evolutionary development of visual systems across species',
        date: 'March 2024',
        topics: ['biology'],
        operations: ['morphogenesis'],
    },
    {
        name: 'pacemaker accumulator',
        link: '/playgrounds/pacemaker-accumulator',
        description: 'cellular timing through pacemaker-accumulator mechanisms',
        date: 'March 2024',
        topics: ['biology', 'neuroscience'],
        operations: ['anatomy'],
    },
    {
        name: 'CPT variance',
        link: '/playgrounds/cpt-variance',
        description: 'symmetry exploration of charge, parity, and time reversal',
        date: 'March 2024',
        topics: ['physics'],
        operations: ['symmetry'],
    },
    {
        name: 'refractive computation',
        link: '/playgrounds/refractive-computation',
        description: 'multiple logical operations simultaneously at different frequencies',
        date: 'March 2024',
        topics: ['physics', 'computer-science'],
        operations: ['anatomy', 'symmetry'],
    },
    {
        name: 'metamaterials',
        link: '/playgrounds/metamaterials',
        description: 'materials engineered to exhibit life-like properties',
        date: 'March 2024',
        topics: ['physics', 'biology'],
        operations: ['morphogenesis'],
    },
    {
        name: 'lifesong',
        link: '/playgrounds/lifesong',
        description: 'musical patterns that emerge from biological processes',
        date: 'March 2024',
        topics: ['biology', 'aesthetics'],
        operations: ['morphogenesis'],
    },
    {
        name: 'vote no',
        link: '/playgrounds/vote-no',
        description: 'exploring democratic resistance and the power of rejection',
        date: 'March 2024',
        topics: ['political-science'],
        operations: ['tension'],
    },
    {
        name: 'everything... relevant',
        link: '/playgrounds/everything-relevant',
        description: 'unified field theory and emergent physics from fundamental equations',
        date: 'March 2024',
        topics: ['physics', 'mathematics'],
        operations: ['landscape', 'symmetry'],
    },
    {
        name: 'Raupian morphospace',
        link: '/playgrounds/raupian-morphospace',
        description: 'coiling models',
        date: 'April 2025',
        topics: ['biology', 'mathematics'],
        operations: ['landscape'],
    },
    {
        name: 'Hsp90 canalization',
        link: '/playgrounds/hsp90-canalization',
        description: 'chaperone-driven canalization of latent phenotypic variation',
        date: 'April 2025',
        topics: ['biology'],
        operations: ['landscape', 'threshold'],
    },
    {
        name: 'Lefebvrian conscience',
        link: '/playgrounds/lefebvrian-conscience',
        description: 'algebra of conscience',
        date: 'May 2025',
        topics: ['philosophy', 'psychology'],
        operations: ['landscape', 'anatomy'],
    },
    {
        name: 'bifurcation speciation',
        link: '/playgrounds/bifurcation-speciation',
        description: 'sympatric and allopatric speciation through bifurcation',
        date: 'May 2025',
        topics: ['biology', 'mathematics'],
        operations: ['threshold'],
    },
    {
        name: 'stochastic justice',
        link: '/playgrounds/stochastic-justice',
        description: 'fairness through randomness in corrupt systems',
        date: 'June 2025',
        topics: ['political-science', 'mathematics'],
        operations: ['anatomy', 'tension'],
    },
    {
        name: 'trauma-eustress dynamics',
        link: '/playgrounds/trauma-eustress-dynamics',
        description: 'constriction and expansion influence on post-trauma trajectories',
        date: 'June 2025',
        topics: ['psychology'],
        operations: ['landscape', 'tension'],
    },
    {
        name: 'open source sustainability',
        link: '/playgrounds/open-source-sustainability',
        description: 'pressure dynamics in open source license transitions',
        date: 'June 2025',
        topics: ['economics', 'computer-science'],
        operations: ['tension', 'threshold'],
    },
    {
        name: 'resentment against desire',
        link: '/playgrounds/resentment-against-desire',
        description: 'the psychology of fairness in the ultimatum game',
        date: 'June 2025',
        topics: ['psychology', 'economics'],
        operations: ['tension', 'anatomy'],
    },
    {
        name: 'debt singularity',
        link: '/playgrounds/debt-singularity',
        description: 'phase transitions of debt through economic conditions',
        date: 'June 2025',
        topics: ['economics'],
        operations: ['threshold'],
    },
    {
        name: 'entropy caf\u00e9',
        link: '/playgrounds/entropy-cafe',
        description: 'entropy and complexity through coffee mixing metaphor',
        date: 'July 2025',
        topics: ['physics', 'chemistry'],
        operations: ['morphogenesis'],
    },
    {
        name: 'geometry becoming topology',
        link: '/playgrounds/geometry-becoming-topology',
        description: 'the transformation from geometric to topological properties',
        date: 'July 2025',
        topics: ['mathematics'],
        operations: ['symmetry', 'threshold'],
    },
    {
        name: 'crystallographic groups',
        link: '/playgrounds/crystallographic-groups',
        description: 'symmetry patterns in 2D, 3D, and 4D',
        date: 'July 2025',
        topics: ['mathematics', 'physics'],
        operations: ['symmetry'],
    },
    {
        name: 'story-suffering coherence',
        link: '/playgrounds/story-suffering-coherence',
        description: 'narrative emergence from suffering integration',
        date: 'July 2025',
        topics: ['psychology', 'philosophy'],
        operations: ['morphogenesis', 'tension'],
    },
    {
        name: 'ramsey ports',
        link: '/playgrounds/ramsey-ports',
        description: 'welfare economics of airport pricing strategies',
        date: 'July 2025',
        topics: ['economics'],
        operations: ['anatomy'],
    },
    {
        name: 'expected free energy',
        link: '/playgrounds/expected-free-energy',
        description: 'Monte Carlo visualization of active inference',
        date: 'July 2025',
        topics: ['neuroscience', 'physics'],
        operations: ['landscape', 'anatomy'],
    },
    {
        name: 'criticality',
        link: '/playgrounds/criticality',
        description: 'branching processes and distance-to-criticality metrics',
        date: 'July 2025',
        topics: ['physics', 'mathematics'],
        operations: ['threshold', 'landscape'],
    },
    {
        name: 'meaning autogenesis',
        link: '/playgrounds/meaning-autogenesis',
        description: 'biosemiotic emergence from molecule to sign',
        date: 'July 2025',
        topics: ['biology', 'philosophy'],
        operations: ['morphogenesis'],
    },
    {
        name: 'agency erosion',
        link: '/playgrounds/agency-erosion',
        description: 'identity substitution dynamics in amplified environments',
        date: 'July 2025',
        topics: ['psychology', 'sociology'],
        operations: ['tension', 'threshold'],
    },
    {
        name: 'berkshire engine',
        link: '/playgrounds/berkshire-engine',
        description: 'insurance float as investment capital',
        date: 'August 2025',
        topics: ['economics'],
        operations: ['anatomy'],
    },
    {
        name: 'authoritarian paternalism',
        link: '/playgrounds/authoritarian-paternalism',
        description: 'paternal authority and citizen support dynamics',
        date: 'August 2025',
        topics: ['political-science', 'sociology'],
        operations: ['tension'],
    },
    {
        name: 'tuition resentment',
        link: '/playgrounds/tuition-resentment',
        description: 'high-tuition psychodynamics and attribution of blame',
        date: 'August 2025',
        topics: ['psychology', 'economics'],
        operations: ['tension', 'anatomy'],
    },
    {
        name: 'truth-violence dynamics',
        link: '/playgrounds/truth-violence-dynamics',
        description: 'parrhesia suppression through pressure and punitive support dynamics',
        date: 'August 2025',
        topics: ['political-science', 'philosophy'],
        operations: ['tension'],
    },
    {
        name: 'neural cellular automaton',
        link: '/playgrounds/neural-cellular-automaton',
        description: 'neural networks evolved through cellular automaton rules',
        date: 'August 2025',
        topics: ['computer-science', 'biology'],
        operations: ['morphogenesis'],
    },
    {
        name: 'scarcity over technology',
        link: '/playgrounds/scarcity-over-technology',
        description: 'economy as the derivative of scarcity with respect to technology',
        date: 'September 2025',
        topics: ['economics'],
        operations: ['anatomy'],
    },
    {
        name: 'PLR harmony',
        link: '/playgrounds/plr-harmony',
        description: 'neo-Riemannian PLR transformations and triadic harmony',
        date: 'September 2025',
        topics: ['mathematics', 'aesthetics'],
        operations: ['symmetry'],
    },
    {
        name: 'ownership parity rule',
        link: '/playgrounds/ownership-parity-rule',
        description: 'matching equity purchases with consumer technology spending',
        date: 'October 2025',
        topics: ['economics'],
        operations: ['anatomy'],
    },
    {
        name: 'subconscious state space',
        link: '/playgrounds/subconscious-state-space',
        description: 'molecular-scale modulation of conscious access and awareness',
        date: 'October 2025',
        topics: ['neuroscience', 'psychology'],
        operations: ['landscape', 'threshold'],
    },
    {
        name: 'social propagation',
        link: '/playgrounds/social-propagation',
        description: 'policy interventions reducing viral political manipulation',
        date: 'October 2025',
        topics: ['political-science', 'sociology'],
        operations: ['tension', 'anatomy'],
    },
    {
        name: 'placebo-nocebo dynamics',
        link: '/playgrounds/placebo-nocebo-dynamics',
        description: 'precision weighting in placebo analgesia and nocebo responses',
        date: 'October 2025',
        topics: ['neuroscience', 'psychology'],
        operations: ['anatomy', 'tension'],
    },
    {
        name: 'space between algorithms',
        link: '/playgrounds/space-between-algorithms',
        description: 'intra- and inter-algorithm freedom through policy manifolds and goal slack',
        date: 'November 2025',
        topics: ['computer-science', 'philosophy'],
        operations: ['landscape', 'anatomy'],
    },
    {
        name: 'algorithmic monodominance',
        link: '/playgrounds/algorithmic-monodominance',
        description: 'phase transitions from concave to convex returns in algorithmic competition',
        date: 'November 2025',
        topics: ['computer-science', 'economics'],
        operations: ['threshold', 'tension'],
    },
    {
        name: 'closedness adverse selection',
        link: '/playgrounds/closedness-adverse-selection',
        description: 'how no-criticism constraints filter entrants toward lower moral aversion',
        date: 'November 2025',
        topics: ['political-science', 'sociology'],
        operations: ['threshold', 'tension'],
    },
    {
        name: 'logical morphogenesis',
        link: '/playgrounds/logical-morphogenesis',
        description: 'truth-value rhythms from self-referential sentences',
        date: 'December 2025',
        topics: ['mathematics', 'philosophy'],
        operations: ['morphogenesis', 'symmetry'],
    },
    {
        name: 'unknot studio',
        link: '/playgrounds/unknot-studio',
        description: 'torus knots, connected sums, and projection invariants',
        date: 'December 2025',
        topics: ['mathematics'],
        operations: ['symmetry', 'landscape'],
    },
    {
        name: 'Cipolla quadrant',
        link: '/playgrounds/cipolla-quadrant',
        description: 'stupidity, intelligence, helplessness, and banditry distributions',
        date: 'December 2025',
        topics: ['psychology', 'sociology'],
        operations: ['landscape', 'anatomy'],
    },
    {
        name: 'Chladni generator',
        link: '/playgrounds/chladni-generator',
        description: 'standing waves, reaction-diffusion, and morphogenesis patterns',
        date: 'December 2025',
        topics: ['physics', 'mathematics', 'aesthetics'],
        operations: ['morphogenesis', 'symmetry'],
    },
    {
        name: 'do-calculus',
        link: '/playgrounds/do-calculus',
        description: 'Judea Pearl\'s interventional framework for causal inference on spiking neurons',
        date: 'December 2025',
        topics: ['computer-science', 'neuroscience'],
        operations: ['anatomy'],
    },
    {
        name: 'activation functions lab',
        link: '/playgrounds/activation-functions-lab',
        description: 'invent, explore, and compare neural network activation functions',
        date: 'January 2026',
        topics: ['computer-science', 'mathematics'],
        operations: ['landscape', 'anatomy'],
    },
    {
        name: 'geometry of fragmentation',
        link: '/playgrounds/geometry-of-fragmentation',
        description: 'Plato\'s cube and the natural geometry of fracture',
        date: 'January 2026',
        topics: ['mathematics', 'physics'],
        operations: ['morphogenesis', 'symmetry'],
    },
    {
        name: 'descent & closure',
        link: '/playgrounds/descent-and-closure',
        description: 'from local micro-events to autonomous macro-processes via sheaf theory',
        date: 'January 2026',
        topics: ['mathematics'],
        operations: ['symmetry', 'anatomy'],
    },
    {
        name: 'kernel smoothing',
        link: '/playgrounds/kernel-smoothing',
        description: 'attention as kernel smoothing: similarity-to-weight mapping',
        date: 'January 2026',
        topics: ['computer-science', 'mathematics'],
        operations: ['anatomy', 'symmetry'],
    },
    {
        name: 'nested observer windows',
        link: '/playgrounds/nested-observer-windows',
        description: 'multi-scale oscillator coupling for hierarchical consciousness',
        date: 'January 2026',
        topics: ['neuroscience', 'physics'],
        operations: ['landscape', 'anatomy'],
    },
    {
        name: 'gait gambit',
        link: '/playgrounds/gait-gambit',
        description: 'a computational model of gait selection',
        date: 'February 2026',
        topics: ['biology', 'physics'],
        operations: ['anatomy', 'threshold'],
    },
    {
        name: 'polity coalition attractors',
        link: '/playgrounds/polity-coalition-attractors',
        description: 'basins of inclusion versus exclusion under stress, norms, and contact',
        date: 'February 2026',
        topics: ['political-science', 'sociology'],
        operations: ['landscape', 'tension'],
    },
    {
        name: 'bordism to action',
        link: '/playgrounds/bordism-to-action',
        description: 'comparing classical mechanics with fully local TQFT',
        date: 'February 2026',
        topics: ['mathematics', 'physics'],
        operations: ['symmetry', 'anatomy'],
    },
    {
        name: 'order-theoretic ontology',
        link: '/playgrounds/order-theoretic-ontology',
        description: 'build ontologies as posets and detect structural leaks',
        date: 'February 2026',
        topics: ['mathematics', 'philosophy'],
        operations: ['anatomy', 'symmetry'],
    },
    {
        name: 'hydride anomaly',
        link: '/playgrounds/hydride-anomaly',
        description: 'hydrogen bonding and the anomalous thermodynamics of water',
        date: 'February 2026',
        topics: ['physics', 'chemistry'],
        operations: ['anatomy', 'threshold'],
    },
    {
        name: 'trust-transaction spectrum',
        link: '/playgrounds/trust-transaction-spectrum',
        description: 'strategic posture optimization for small states under geopolitical constraints',
        date: 'February 2026',
        topics: ['political-science', 'economics'],
        operations: ['landscape', 'threshold'],
    },
];
