import type { Assumption } from '@/components/AssumptionPanel';


export const assumptions: Assumption[] = [
    {
        id: 'euclidean-plane',
        statement:
            'patterns are drawn in the flat Euclidean plane with its standard metric. the 17-group classification is a theorem about isometries of this plane; it does not apply unchanged to the sphere or the hyperbolic plane, where the count of symmetry groups is different (and infinite in the hyperbolic case).',
        citation:
            'Coxeter and Moser, Generators and Relations for Discrete Groups; the spherical and hyperbolic analogues have their own enumerations.',
        confidence: 'established',
        falsifiability:
            'on a curved surface the crystallographic restriction changes, so 5-fold and higher rotations become possible and the figure of 17 no longer holds.',
    },
    {
        id: 'infinite-lattice',
        statement:
            'each group is treated as an infinite, perfectly periodic tiling. the canvas only renders a finite window, but every property (point-group order, rotation order, glide presence) is read from the idealised infinite pattern, not from the visible patch.',
        citation:
            'standard definition: a wallpaper group is a discrete cocompact group of plane isometries with a rank-2 translation subgroup (Bieberbach).',
        confidence: 'established',
        falsifiability:
            'a finite tiling, or a quasiperiodic one with no translation lattice, is not a wallpaper group at all; the classification assumes genuine two-dimensional periodicity.',
    },
    {
        id: 'crystallographic-restriction',
        statement:
            'only rotations of order 1, 2, 3, 4, and 6 occur. this is the crystallographic restriction theorem: a rotation order compatible with a translation lattice forces 2 cos(2 pi / n) to be an integer, which excludes 5-fold and orders above 6.',
        citation:
            'crystallographic restriction theorem (Barlow; standard in the International Tables for Crystallography).',
        confidence: 'established',
        falsifiability:
            'observing a periodic crystal with true 5-fold translational symmetry would break this; quasicrystals exhibit 5-fold diffraction precisely because they are not periodic lattices.',
    },
    {
        id: 'classification-complete',
        statement:
            'the 17 groups are exactly complete: no two of them are equivalent under affine conjugacy, and no eighteenth group exists. the playground enumerates all 17 and treats the set as closed.',
        citation:
            'Fedorov 1891 proved completeness; Pólya 1924 and Niggli rederived it independently.',
        confidence: 'established',
        falsifiability:
            'any plane symmetry pattern that could not be assigned to one of these 17 groups would refute the classification; none has ever been found.',
    },
    {
        id: 'motif-orbit-representation',
        statement:
            'the visual symmetry is generated by laying out one base motif (the letter R) and its orbit under the cell point group, copied across the translation lattice. the number of drawn copies per cell equals the point-group order, and reflections are realised by mirroring the motif.',
        citation:
            'standard orbit construction: a pattern equals the orbit of a fundamental-domain motif under the full group action.',
        confidence: 'established',
        falsifiability:
            'if the drawn orbit had fewer or more copies than the point-group order, or omitted a generator, the rendered tiling would carry a different symmetry group than its label claims.',
    },
    {
        id: 'idealised-glides-as-offsets',
        statement:
            'glide reflections are approximated by translating a reflected motif by half a lattice vector (for example pg offsets the mirrored copy by a/2). this captures the glide visually but the rendering is a discrete sampling, not a continuous glide line.',
        citation:
            'modelling simplification; a true glide is a reflection composed with a half-period translation along the mirror axis.',
        confidence: 'contested',
        falsifiability:
            'a viewer measuring the exact glide-line position against the continuous definition would find the discrete half-cell offset is an approximation chosen for legibility.',
    },
    {
        id: 'lattice-geometry-fixed',
        statement:
            'lattice geometry is hard-coded per group: oblique and rectangular cells use a square grid spacing, while 3-fold and 6-fold groups switch to a hexagonal lattice via the shear x = i a + j a / 2. cell shape is not a free parameter the user can vary.',
        citation:
            'each wallpaper group constrains its Bravais lattice class (oblique, rectangular, centred, square, hexagonal).',
        confidence: 'contested',
        falsifiability:
            'continuously deforming the cell can change which group a pattern belongs to; fixing the geometry means the playground shows one representative cell per group, not the full deformation family.',
    },
    {
        id: 'symmetry-only-no-color',
        statement:
            'the playground encodes only ordinary (uncoloured) plane symmetry. it ignores colour symmetry, in which a recolouring permutation accompanies each isometry and the 17 groups expand into the 46 two-colour groups.',
        citation:
            'Woods and later authors enumerated the 46 two-coloured plane groups; the uncoloured case is the base classification used here.',
        confidence: 'speculative',
        falsifiability:
            'a pattern whose symmetry only holds when colours are permuted would need the coloured-group framework; the single-colour motif here cannot express it.',
    },
];
