import type { CalibrationResult } from '@/components/CalibrationPanel';

import {
    WALLPAPER_GROUP_COUNT,
    rotationOrder,
    pointGroupOrder,
    hasReflection,
    reflectionGroupCount,
} from './logic';

/**
 * Calibration against the closed, exact classification of the 17 wallpaper
 * groups. Every `predicted` value is COMPUTED by the logic module from the same
 * group specs the canvas draws; `expected` is the textbook value (Coxeter and
 * Moser, Generators and Relations for Discrete Groups; the International Tables
 * for Crystallography). Because these are exact integers, error is expected to
 * be zero in every row.
 */
export function buildCalibration(): CalibrationResult[] {
    return [
        {
            name: 'count of plane groups',
            description: 'the complete classification yields exactly 17 wallpaper groups (Fedorov 1891).',
            predicted: WALLPAPER_GROUP_COUNT,
            expected: 17,
            source: 'Fedorov 1891; Pólya 1924 (independent rediscovery of the 17 plane groups)',
        },
        {
            name: 'p6 rotation order',
            description: 'p6 is generated by a 6-fold rotation, the highest order the plane allows.',
            predicted: rotationOrder('p6'),
            expected: 6,
            source: 'crystallographic restriction theorem; International Tables for Crystallography',
        },
        {
            name: 'p4 rotation order',
            description: 'p4 carries a 4-fold rotation centre on a square lattice.',
            predicted: rotationOrder('p4'),
            expected: 4,
            source: 'International Tables for Crystallography, plane group p4',
        },
        {
            name: 'p1 rotation order',
            description: 'p1 is the translation-only group; its only rotation is the trivial 1-fold identity.',
            predicted: rotationOrder('p1'),
            expected: 1,
            source: 'International Tables for Crystallography, plane group p1',
        },
        {
            name: 'pm contains a reflection',
            description: 'pm is generated by a translation and a mirror line; reflection present (encoded as 1).',
            predicted: hasReflection('pm') ? 1 : 0,
            expected: 1,
            source: 'International Tables for Crystallography, plane group pm',
        },
        {
            name: 'p6m point-group order',
            description: 'p6m has the largest point group of the 17: the dihedral group of order 12 (6 rotations and 6 mirrors).',
            predicted: pointGroupOrder('p6m'),
            expected: 12,
            source: 'Coxeter and Moser, Generators and Relations for Discrete Groups',
        },
        {
            name: 'number of mirror groups',
            description: 'of the 17 groups, exactly 10 contain a mirror reflection; the other 7 do not.',
            predicted: reflectionGroupCount(),
            expected: 10,
            source: 'enumeration over the 17 plane groups (International Tables for Crystallography)',
        },
    ];
}
